### ISSUE TITLE
关于数据集处理的问题

### ISSUE THREAD

**Issue by Maribel-Hearn** [Junewang0614/ColaRec#1]
你好，我对你们的工作很感兴趣，也试着运行了phone数据集，但我也想尝试其他数据集的效果，所以我想询问是否有处理数据集的相关代码？尤其是corpus_512.json和cid_neg_dict.json这样的文件，代码里也提到了预训练获得的embeddings_single.pth，想请教跟这些文件相关的来源，非常感谢！

**Comment by Junewang0614** [comment]
你好，corpus_512.json文件是保存了每个item的信息的json文件，其中“atom_id”表示每个item的原子id，”content“是item的文本描述，这两部分需要根据原始的公开数据集文件来实现具体的数据处理代码。”cid“表示的是论文中的GID，就是根据hierarchical_cluster.py层次聚类获得。

embeddings_single.pth文件中保存了GID聚类所使用的item的嵌入表示，如论文所说是通过预训练的CF模型获得，phone数据集中所使用的对应文件已经上传到这个仓库中[link](https://github.com/Junewang0614/ColaRec/tree/main/datasets/phone)，可以参考一下。

cid_neg_dict.json是为了方便indexing任务获得和target item在GID上有重叠前缀的正样本，保存了每个item的GID前缀重叠1位(fst)和重叠2位(sec)的其他item，这个就是基于pandas统计处理的。

希望以上的回答能对您有帮助~

**Comment by Maribel-Hearn** [comment]
> 你好，corpus_512.json文件是保存了每个item的信息的json文件，其中“atom_id”表示每个item的原子id，”content“是item的文本描述，这两部分需要根据原始的公开数据集文件来实现具体的数据处理代码。”cid“表示的是论文中的GID，就是根据hierarchical_cluster.py层次聚类获得。
> 
> embeddings_single.pth文件中保存了GID聚类所使用的item的嵌入表示，如论文所说是通过预训练的CF模型获得，phone数据集中所使用的对应文件已经上传到这个仓库中[link](https://github.com/Junewang0614/ColaRec/tree/main/datasets/phone)，可以参考一下。
> 
> cid_neg_dict.json是为了方便indexing任务获得和target item在GID上有重叠前缀的正样本，保存了每个item的GID前缀重叠1位(fst)和重叠2位(sec)的其他item，这个就是基于pandas统计处理的。
> 
> 希望以上的回答能对您有帮助~

非常感谢您的回答！不过我还是有一点疑问，还想询问几个问题：
对于corpus_512.json文件，是否是先通过原始的Amazon数据集先得到atom_id,content数据添加入corpus_512.json后，再执行hierarchical_cluster.py将GID信息添加进来吗？
另外embeddings_single.pth在论文中是由LightGCN得到的，GitHub上关于LightGCN有很多实现，我不清楚不同的实现会不会影响运行结果等，请问能否提供论文使用的源码链接让我去参考一下？另外在训练embedding时是否不用区分训练集，验证集和测试集，直接将所有交互数据都输入，然后最终得到embedding吗？
希望能够得到您的回答，非常感谢!

**Comment by Junewang0614** [comment]
> > 你好，corpus_512.json文件是保存了每个item的信息的json文件，其中“atom_id”表示每个item的原子id，”content“是item的文本描述，这两部分需要根据原始的公开数据集文件来实现具体的数据处理代码。”cid“表示的是论文中的GID，就是根据hierarchical_cluster.py层次聚类获得。
> > embeddings_single.pth文件中保存了GID聚类所使用的item的嵌入表示，如论文所说是通过预训练的CF模型获得，phone数据集中所使用的对应文件已经上传到这个仓库中[link](https://github.com/Junewang0614/ColaRec/tree/main/datasets/phone)，可以参考一下。
> > cid_neg_dict.json是为了方便indexing任务获得和target item在GID上有重叠前缀的正样本，保存了每个item的GID前缀重叠1位(fst)和重叠2位(sec)的其他item，这个就是基于pandas统计处理的。
> > 希望以上的回答能对您有帮助~
> 
> 非常感谢您的回答！不过我还是有一点疑问，还想询问几个问题： 对于corpus_512.json文件，是否是先通过原始的Amazon数据集先得到atom_id,content数据添加入corpus_512.json后，再执行hierarchical_cluster.py将GID信息添加进来吗？ 另外embeddings_single.pth在论文中是由LightGCN得到的，GitHub上关于LightGCN有很多实现，我不清楚不同的实现会不会影响运行结果等，请问能否提供论文使用的源码链接让我去参考一下？另外在训练embedding时是否不用区分训练集，验证集和测试集，直接将所有交互数据都输入，然后最终得到embedding吗？ 希望能够得到您的回答，非常感谢!

1. 是的，corpus_512.json文件中只有GID是hierarchical_cluster.py构造获得的，其他部分源自原始数据数据集。
2. LightGCN模型是基于RecBole实现，具体实现链接为[LINK](https://github.com/RUCAIBox/RecBole)，无论是训练LightGCN以获得GID还是训练最终的生成模型，我们都只会使用训练集进行训练以防止数据泄露。

**Comment by Maribel-Hearn** [comment]
> > > 你好，corpus_512.json文件是保存了每个item的信息的json文件，其中“atom_id”表示每个item的原子id，”content“是item的文本描述，这两部分需要根据原始的公开数据集文件来实现具体的数据处理代码。”cid“表示的是论文中的GID，就是根据hierarchical_cluster.py层次聚类获得。
> > > embeddings_single.pth文件中保存了GID聚类所使用的item的嵌入表示，如论文所说是通过预训练的CF模型获得，phone数据集中所使用的对应文件已经上传到这个仓库中[link](https://github.com/Junewang0614/ColaRec/tree/main/datasets/phone)，可以参考一下。
> > > cid_neg_dict.json是为了方便indexing任务获得和target item在GID上有重叠前缀的正样本，保存了每个item的GID前缀重叠1位(fst)和重叠2位(sec)的其他item，这个就是基于pandas统计处理的。
> > > 希望以上的回答能对您有帮助~
> > 
> > 
> > 非常感谢您的回答！不过我还是有一点疑问，还想询问几个问题： 对于corpus_512.json文件，是否是先通过原始的Amazon数据集先得到atom_id,content数据添加入corpus_512.json后，再执行hierarchical_cluster.py将GID信息添加进来吗？ 另外embeddings_single.pth在论文中是由LightGCN得到的，GitHub上关于LightGCN有很多实现，我不清楚不同的实现会不会影响运行结果等，请问能否提供论文使用的源码链接让我去参考一下？另外在训练embedding时是否不用区分训练集，验证集和测试集，直接将所有交互数据都输入，然后最终得到embedding吗？ 希望能够得到您的回答，非常感谢!
> 
> 1. 是的，corpus_512.json文件中只有GID是hierarchical_cluster.py构造获得的，其他部分源自原始数据数据集。
> 2. LightGCN模型是基于RecBole实现，具体实现链接为[LINK](https://github.com/RUCAIBox/RecBole)，无论是训练LightGCN以获得GID还是训练最终的生成模型，我们都只会使用训练集进行训练以防止数据泄露。

好的，麻烦你回答了，非常感谢你的解答！
